// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Heartbeat
	Packet
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Packet_Type int32

const (
	Packet_HEARTBEAT Packet_Type = 1
)

var Packet_Type_name = map[int32]string{
	1: "HEARTBEAT",
}
var Packet_Type_value = map[string]int32{
	"HEARTBEAT": 1,
}

func (x Packet_Type) Enum() *Packet_Type {
	p := new(Packet_Type)
	*p = x
	return p
}
func (x Packet_Type) String() string {
	return proto.EnumName(Packet_Type_name, int32(x))
}
func (x *Packet_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Packet_Type_value, data, "Packet_Type")
	if err != nil {
		return err
	}
	*x = Packet_Type(value)
	return nil
}
func (Packet_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Heartbeat struct {
	Heartbeat        *bool  `protobuf:"varint,1,opt,name=heartbeat" json:"heartbeat,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Heartbeat) GetHeartbeat() bool {
	if m != nil && m.Heartbeat != nil {
		return *m.Heartbeat
	}
	return false
}

type Packet struct {
	// Require type to be specified
	Type *Packet_Type `protobuf:"varint,1,req,name=type,enum=Packet_Type" json:"type,omitempty"`
	// One of the following will be filled in
	Heartbeat        *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat" json:"heartbeat,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Packet) GetType() Packet_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Packet_HEARTBEAT
}

func (m *Packet) GetHeartbeat() *Heartbeat {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "Heartbeat")
	proto.RegisterType((*Packet)(nil), "Packet")
	proto.RegisterEnum("Packet_Type", Packet_Type_name, Packet_Type_value)
}

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe4, 0xe2, 0xf4, 0x48, 0x4d, 0x2c, 0x2a, 0x49,
	0x4a, 0x4d, 0x2c, 0x11, 0x92, 0xe1, 0xe2, 0xcc, 0x80, 0x71, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x82, 0x10, 0x02, 0x4a, 0xd9, 0x5c, 0x6c, 0x01, 0x89, 0xc9, 0xd9, 0xa9, 0x25, 0x42, 0x0a, 0x5c,
	0x2c, 0x25, 0x95, 0x05, 0xa9, 0x40, 0x25, 0x4c, 0x1a, 0x7c, 0x46, 0x3c, 0x7a, 0x10, 0x61, 0xbd,
	0x10, 0xa0, 0x58, 0x10, 0x58, 0x46, 0x48, 0x03, 0xd9, 0x24, 0x26, 0xa0, 0x49, 0xdc, 0x46, 0x5c,
	0x7a, 0x70, 0x8b, 0x90, 0x4d, 0x15, 0xe5, 0x62, 0x01, 0xe9, 0x13, 0xe2, 0x05, 0x3a, 0xc4, 0xd5,
	0x31, 0x28, 0xc4, 0xc9, 0xd5, 0x31, 0x44, 0x80, 0x11, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x0a,
	0x60, 0xbf, 0xa4, 0x00, 0x00, 0x00,
}
